export const GET_ACTUAL_ALLOCATIONS: string = 'GET_ACTUAL_ALLOCATIONS';
export const GET_PENDING_ACTUAL_ALLOCATIONS: string =
  'GET_PENDING_ACTUAL_ALLOCATIONS';
export const GET_ACTUAL_ALLOCATIONS_STATUSES: string =
  'GET_ACTUAL_ALLOCATIONS_STATUSES';
export const GET_ACTUAL_STATUS: string = 'GET_ACTUAL_STATUS';
export const UPDATE_ACTUAL_STATUS: string = 'UPDATE_ACTUAL_STATUS';
export const CONFIRM_ACTUAL_ALLOCATIONS: string = 'CONFIRM_ACTUAL_ALLOCATIONS';
