
export const FETCH_TOTAL_ALLOCATIONS = 'FETCH_TOTAL_ALLOCATIONS';
export const FETCH_TOTAL_ALLOCATION_COST = 'FETCH_TOTAL_ALLOCATION_COST';
export const FETCH_TOTAL_ALLOCATIONS_SUMMARY =
  'FETCH_TOTAL_ALLOCATIONS_SUMMARY';
export const FETCH_TOTAL_ALLOCATIONS_TILL_DATE = 'FETCH_TOTAL_ALLOCATIONS_TILL_DATE';
