export const FETCH_ALL_RESOURCES_DETAIL = 'FETCH_ALL_RESOURCES_DETAIL';
export const FETCH_RESOURCE_DETAILS = 'FETCH_RESOURCE_DETAILS';
export const FETCH_ALL_RESOURCES_DETAIL_SUCCESS =
  'FETCH_ALL_RESOURCES_DETAIL_SUCCESS';
