export const FETCH_ALL_SETTINGS = 'FETCH_ALL_SETTINGS';
export const FETCH_SCALAR_SETTINGS = 'FETCH_SCALAR_SETTINGS';
export const ADD_SCALAR_SETTING = 'ADD_SCALAR_SETTING';
export const UPDATE_SCALAR_SETTING = 'UPDATE_SCALAR_SETTING';
export const FETCH_PROJECT_TYPES = 'FETCH_PROJECT_TYPES';
export const ADD_PROJECT_TYPE = 'ADD_PROJECT_TYPE';
export const UPDATE_PROJECT_TYPE = 'UPDATE_PROJECT_TYPE';
export const DELETE_PROJECT_TYPE = 'DELETE_PROJECT_TYPE';
