
export const FETCH_BUSINESS_IMPACT = 'FETCH_BUSINESS_IMPACT';
export const CREATE_BUSINESS_IMPACT = 'CREATE_BUSINESS_IMPACT';
export const UPDATE_BUSINESS_IMPACT = 'UPDATE_BUSINESS_IMPACT';
export const DELETE_BUSINESS_IMPACT = 'DELETE_BUSINESS_IMPACT';


export const FETCH_BUSINESS_IMPACT_TYPE = 'FETCH_BUSINESS_IMPACT_TYPE';