export const FETCH_EMPLOYEE_RATES = 'FETCH_EMPLOYEE_RATES';
export const CREATE_EMPLOYEE_RATES = 'CREATE_EMPLOYEE_RATES';
export const UPDATE_EMPLOYEE_RATES = 'UPDATE_EMPLOYEE_RATES';
export const DELETE_EMPLOYEE_RATES = 'DELETE_EMPLOYEE_RATES';


