export const FETCH_ORGANISATIONS = 'FETCH_ORGANISATIONS';
export const CREATE_ORGANISATION = 'CREATE_ORGANISATIONS'; 
export const UPDATE_ORGANISATION = 'UPDATE_ORGANISATIONS';
export const DELETE_ORGANISATION = 'DELETE_ORGANISATIONS';

export const FETCH_ORGANISATIONS_RESOURCES = 'FETCH_ORGANISATIONS_RESOURCES';
