export const FETCH_PORTFOLIOS = 'FETCH_PORTFOLIOS';
export const CREATE_PORTFOLIOS = 'CREATE_PORTFOLIOS';
export const UPDATE_PORTFOLIOS = 'UPDATE_PORTFOLIOS';
export const DELETE_PORTFOLIOS = 'DELETE_PORTFOLIOS';
