export const FETCH_ROLES = 'FETCH_ROLES';
export const CREATE_ROLE = 'CREATE_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';

export const FETCH_ROLESASSIGNMENTS = 'FETCH_ROLESASSIGNMENTS';
export const CREATE_ROLESASSIGNMENT = 'CREATE_ROLESASSIGNMENT';
export const UPDATE_ROLESASSIGNMENT = 'UPDATE_ROLESASSIGNMENT';
export const DELETE_ROLESASSIGNMENT = 'DELETE_ROLESASSIGNMENT';

export const FETCH_PRIVILEGES = 'FETCH_PRIVILEGES';
export const CREATE_PRIVILEGE = 'CREATE_PRIVILEGE';
export const UPDATE_PRIVILEGE = 'UPDATE_PRIVILEGE';
export const DELETE_PRIVILEGE = 'DELETE_PRIVILEGE';

export const FETCH_PRIVILEGEASSIGNMENTS = 'FETCH_PRIVILEGEASSIGNMENTS';
export const CREATE_PRIVILEGEASSIGNMENT = 'CREATE_PRIVILEGEASSIGNMENT';
export const UPDATE_PRIVILEGEASSIGNMENT = 'UPDATE_PRIVILEGEASSIGNMENT';
export const DELETE_PRIVILEGEASSIGNMENT = 'DELETE_PRIVILEGEASSIGNMENT';
