export const FETCH_SAVED_REPORTS = 'FETCH_SAVED_REPORTS';
export const SAVE_REPORTS = 'SAVE_REPORTS';
export const DELETE_SAVED_REPORT = 'DELETE_SAVED_REPORT';
export const UPDATE_SAVED_REPORT = 'UPDATE_SAVED_REPORT';
