export const FETCH_USER_PREFERENCES = 'FETCH_USER_PREFERENCES';
export const ADD_USER_PREFERENCES = 'ADD_USER_PREFERENCES';
export const UPDATE_USER_PREFERENCES = 'UPDATE_USER_PREFERENCES';
export const SET_USER_PREFERENCES = 'SET_USER_PREFERENCES';
